// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.cs.CommonEntitiesConv {
    public class VersionInfo {
        public static string appVersion = "2.2.2";
        public static string longVersion = "2.2.2-20230729-4aa26f22";
        public static string buildDate = "20230729";
    }
}
