// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.cs.CommonEntitiesConv {
    public class VersionInfo {
        public static string appVersion = "2.0.5";
        public static string longVersion = "2.0.5-20220609-9b743fec";
        public static string buildDate = "20220609";
    }
}
