// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.cs.CommonEntities {
    public class VersionInfo {
        public static string appVersion = "2.0.6";
        public static string longVersion = "2.0.6-20220623-3db29425";
        public static string buildDate = "20220623";
    }
}
